# Principales Arquitecturas de Redes Neuronales

En este notebook se explican las arquitecturas mas usadas en aprendizaje profundo: **FNN/ANN-FNN, CNN, RNN y GAN**.
Tambien se incluye una seccion de **optimizadores** y ejemplos simples para entender su comportamiento.

## 1. FNN y ANN-FNN (Red Feedforward)

### Que es
- **ANN (Artificial Neural Network)**: nombre general para redes neuronales artificiales.
- **FNN (Feedforward Neural Network)**: tipo de ANN donde la informacion avanza en una sola direccion (entrada -> capas ocultas -> salida), sin ciclos.

### Como se comporta
- Cada neurona calcula una combinacion lineal y luego aplica una funcion de activacion (ReLU, sigmoid, tanh).
- Aprende fronteras de decision no lineales cuando tiene suficientes capas/neuronas.
- No tiene memoria temporal: no recuerda estados anteriores.

### Ventajas
- Facil de implementar y entrenar en problemas pequenos/medianos.
- Buena base para entender backpropagation y optimizacion.

### Limitaciones
- No aprovecha estructura espacial (imagenes) ni temporal (secuencias).
- Puede sobreajustar si hay muchos parametros y pocos datos.

### Casos de uso
- Clasificacion en datos tabulares: riesgo crediticio, fraude simple, abandono de clientes.
- Regresion: precios, consumo energetico, demanda.
- Clasificacion multiclase basica.

In [2]:
# Ejemplo simple FNN: una capa oculta con NumPy
import numpy as np

np.random.seed(0)
X = np.array([[0.2, 0.8, 0.5]])  # 1 muestra, 3 caracteristicas
W1 = np.random.randn(3, 4) * 0.1
b1 = np.zeros((1, 4))
W2 = np.random.randn(4, 1) * 0.1
b2 = np.zeros((1, 1))

relu = lambda z: np.maximum(0, z)
sigmoid = lambda z: 1 / (1 + np.exp(-z))

h = relu(X @ W1 + b1)
y_hat = sigmoid(h @ W2 + b2)
print("Salida predicha (probabilidad):", y_hat.ravel()[0])

Salida predicha (probabilidad): 0.5054353879348793


## 2. CNN (Red Convolucional)

### Que es
Una red diseñada para datos con estructura espacial (principalmente imagenes).
Usa filtros (kernels) que recorren la entrada para detectar patrones locales.

### Como se comporta
- Las primeras capas detectan bordes y texturas.
- Capas mas profundas detectan partes de objetos y luego objetos completos.
- Operaciones de *pooling* reducen dimensionalidad y aportan cierta invariancia a traslaciones.

### Ventajas
- Reutiliza pesos (convolucion), por eso necesita menos parametros que una red densa para imagenes.
- Excelente rendimiento en vision por computador.

### Limitaciones
- Entrenamiento costoso en computo para modelos grandes.
- Requiere buen volumen de datos o tecnicas de aumento/transfer learning.

### Casos de uso
- Clasificacion de imagenes (gato/perro, tipos de defectos, etc.).
- Deteccion de objetos (personas, carros, placas).
- Diagnostico asistido por imagen medica.

In [3]:
# Ejemplo simple CNN: aplicar un filtro de bordes en una imagen 5x5
import numpy as np

img = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
], dtype=float)

kernel = np.array([
    [-1, -1, -1],
    [-1,  8, -1],
    [-1, -1, -1]
], dtype=float)

out = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        patch = img[i:i+3, j:j+3]
        out[i, j] = np.sum(patch * kernel)

print("Mapa de activacion del filtro de bordes:")
print(out)

Mapa de activacion del filtro de bordes:
[[5. 3. 5.]
 [3. 0. 3.]
 [5. 3. 5.]]


## 3. RNN (Red Recurrente)

### Que es
Arquitectura para datos secuenciales donde cada paso depende de pasos previos.
Mantiene un estado oculto que actua como memoria de corto plazo.

### Como se comporta
- Procesa la secuencia token a token (o paso a paso).
- El estado oculto se actualiza con la entrada actual y el estado anterior.
- En secuencias largas puede sufrir desvanecimiento/explosion de gradientes; por eso LSTM/GRU son variantes comunes.

### Ventajas
- Captura orden y contexto temporal.
- Util en tareas donde el tiempo importa.

### Limitaciones
- Entrenamiento menos paralelizable que modelos puramente feedforward.
- Puede quedarse corta en dependencias muy largas (segun arquitectura).

### Casos de uso
- Prediccion de series de tiempo (demanda, trafico, sensores).
- NLP clasico (sentimiento, etiquetado secuencial).
- Reconocimiento de voz y modelado de audio.

In [4]:
# Ejemplo simple RNN: actualizar estado oculto en una secuencia corta
import numpy as np

np.random.seed(1)
sequence = [0.1, 0.5, -0.2, 0.3]

Wx = 0.7  # peso de entrada
Wh = 0.5  # peso recurrente
b = 0.0
h = 0.0

def tanh(x):
    return np.tanh(x)

for t, x_t in enumerate(sequence, start=1):
    h = tanh(Wx * x_t + Wh * h + b)
    print(f"Paso {t} | entrada={x_t:.2f} | estado_h={h:.4f}")

Paso 1 | entrada=0.10 | estado_h=0.0699
Paso 2 | entrada=0.50 | estado_h=0.3670
Paso 3 | entrada=-0.20 | estado_h=0.0435
Paso 4 | entrada=0.30 | estado_h=0.2277


## 4. GAN (Red Generativa Antagonica)

### Que es
Una GAN tiene dos redes entrenadas en competencia:
- **Generador (G)**: intenta crear muestras sinteticas parecidas a las reales.
- **Discriminador (D)**: intenta distinguir si una muestra es real o generada.

### Como se comporta
- Si D mejora, G recibe una señal mas exigente y aprende a generar mejor.
- Si G mejora, D debe aprender fronteras mas finas entre real/falso.
- El equilibrio ideal ocurre cuando D no puede distinguir bien (aprox. 50%).

### Ventajas
- Alta capacidad para generar datos realistas.
- Muy util para sintetizar datos y aumentar datasets.

### Limitaciones
- Entrenamiento inestable (mode collapse, desbalance G-D).
- Sensible a arquitectura, hiperparametros y criterio de parada.

### Casos de uso
- Generacion de imagenes (rostros, objetos, estilos).
- Super-resolucion y restauracion de imagen.
- Traduccion de dominios (foto <-> pintura, verano <-> invierno).
- Creacion de datos sinteticos para entrenamiento.

In [5]:
# Ejemplo conceptual GAN (pseudoentrenamiento simplificado)
import numpy as np

np.random.seed(42)
real_data = np.random.normal(loc=2.0, scale=0.5, size=1000)
noise = np.random.normal(0, 1, size=1000)
generated_data = 0.8 * noise + 1.2  # salida inicial de un 'generador' simple

print("Media datos reales:", round(real_data.mean(), 3))
print("Media datos generados (inicio):", round(generated_data.mean(), 3))
print("Idea GAN: entrenar para que ambas distribuciones se parezcan cada vez mas.")

Media datos reales: 2.01
Media datos generados (inicio): 1.257
Idea GAN: entrenar para que ambas distribuciones se parezcan cada vez mas.


## 5. Comparacion Rapida

| Arquitectura | Tipo de dato ideal | Fortalezas | Limitaciones |
|---|---|---|---|
| FNN / ANN-FNN | Tabular | Simple y rapida de entrenar | No modela secuencias ni estructura espacial |
| CNN | Imagen / video | Detecta patrones espaciales con alta precision | Requiere mas computo y datos |
| RNN (LSTM/GRU) | Secuencias | Modela dependencia temporal | Entrenamiento mas lento y sensible en secuencias largas |
| GAN | Generacion de datos | Crea muestras realistas | Entrenamiento complejo e inestable |

## 6. Optimizadores en Redes Neuronales

Un optimizador define como se actualizan los pesos para minimizar la funcion de perdida.
La eleccion impacta directamente la velocidad, estabilidad y calidad de convergencia.

### 6.1 Descenso de Gradiente (GD)
- Usa todo el dataset en cada actualizacion.
- Gradiente estable, pero costo computacional alto por iteracion.

### 6.2 SGD (Stochastic Gradient Descent)
- Actualiza con una muestra o mini-batch.
- Mas rapido por iteracion, pero con trayectoria ruidosa.

### 6.3 Momentum
- Acumula direccion de gradientes pasados (inercia).
- Reduce oscilaciones y acelera en superficies alargadas.

### 6.4 RMSprop
- Ajusta tasa de aprendizaje por parametro usando promedio de gradientes cuadrados.
- Util cuando hay gradientes con escalas diferentes (comun en secuencias).

### 6.5 Adam
- Combina Momentum (primer momento) + RMSprop (segundo momento).
- Excelente punto de partida en muchos problemas practicos.

### 6.6 AdamW
- Variante de Adam con *weight decay* desacoplado.
- Suele generalizar mejor que Adam clasico en varios escenarios.

### 6.7 Guia Rapida de Seleccion
- Inicio rapido y buen baseline: **Adam**.
- Mejor control de generalizacion: **SGD + Momentum**.
- Problemas secuenciales o gradientes variables: **RMSprop** o **Adam**.
- Modelos modernos grandes: **AdamW**.

In [6]:
# Ejemplo simple: comparar GD vs Momentum minimizando f(w)=(w-3)^2
import numpy as np

def grad(w):
    return 2 * (w - 3)

# GD
w_gd = 10.0
lr = 0.1
for _ in range(10):
    w_gd -= lr * grad(w_gd)

# Momentum
w_m = 10.0
v = 0.0
beta = 0.9
for _ in range(10):
    v = beta * v + (1 - beta) * grad(w_m)
    w_m -= lr * v

print("w final con GD:", round(w_gd, 4))
print("w final con Momentum:", round(w_m, 4))
print("Minimo teorico en w=3")

w final con GD: 3.7516
w final con Momentum: 5.1498
Minimo teorico en w=3


## 7. Conclusiones

- No existe una arquitectura universalmente mejor: depende del tipo de dato y objetivo.
- FNN es ideal para tabular; CNN para imagen; RNN para secuencias; GAN para generacion de datos.
- Un buen optimizador puede reducir tiempo de entrenamiento y mejorar resultado final.
- En practica, conviene iniciar con un baseline simple y luego aumentar complejidad de forma controlada.